language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

matrix:
  fast_finish: true
  allow_failures:
    python: 3.7-dev

sudo: false

addons:
  apt_packages:
    - libbz2-dev
    - libhdf5-serial-dev
    - liblzo2-dev

before_install:
  - pip install cython
  - python setup.py sdist

install:
  - pip install dist/*.tar.gz
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
  - cd .. && python -m tables.tests.test_all
  - pt2to3 -h
  - ptrepack -h
  - ptdump -h
  - pttree -h

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/58f8a9014ef02f6217ec
    on_success: change
