arch:
    - amd64
language: python
dist: xenial

python:
  #- 3.5
  #- 3.6
  - 3.7
  #- 3.8-dev

addons:
  apt_packages:
    - libbz2-dev
    - libhdf5-serial-dev
    - liblzo2-dev

before_install:
  - pip install cython
  - python setup.py sdist

install:
  - pip install dist/*.tar.gz

script:
  - #cd .. && python -m tables.tests.test_all
  - pt2to3 -h
  - ptrepack -h
  - ptdump -h
  - pttree -h

before_deploy:
  - pip install sphinx sphinx_rtd_theme ipython
  - cd doc
  - make html
  - touch build/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/build
  verbose: true
  on:
    branch: make_docs  # master
    python: 3.7
    #tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/58f8a9014ef02f6217ec
    on_success: change
