environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    # From: https://github.com/astropy/ci-helpers/blob/master/appveyor/windows_sdk.cmd
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\windows_sdk.cmd"

  matrix:
#    - PYTHON: "C:\\Python27_32"
#      PYTHON_VERSION: "2.7"
#      PYTHON_ARCH: "32"
#      CONDA_PY: "27"
#      conda_npy: "18"

#    - python: "c:\\python27_64"
#      PYTHON_VERSION: "2.7"
#      PYTHON_ARCH: "64"
#      CONDA_PY: "27"
#      CONDA_NPY: "18"

#    - PYTHON: "C:\\Python34_32"
#      PYTHON_VERSION: "3.4"
#      PYTHON_ARCH: "32"
#      CONDA_PY: "34"
#      CONDA_NPY: "18"

#    - PYTHON: "C:\\Python34_64"
#      PYTHON_VERSION: "3.4"
#      PYTHON_ARCH: "64"
#      CONDA_PY: "34"
#      CONDA_NPY: "18"

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "111"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - powershell .\\ci\\appveyor\\install.ps1   
  - powershell ./appveyor/missing-headers.ps1
  # install hdf5
  - curl -O http://www.hdfgroup.org/ftp/HDF5/current/bin/windows/hdf5-1.8.17-win64-vs2013-shared.zip
  - unzip hdf5-1.8.17-win64-vs2013-shared.zip
  - cd hdf5
  - msiexec /i HDF5-1.8.17-win64.msi /quiet /qn /norestart /log install.log
  - type install.log
  - cd ..
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"

build: false

test_script:
  #- cmd: conda create --yes -n buildenv python=%PYTHON_VERSION% numexpr cython
  #- cmd: activate buildenv
  - cmd: conda install --yes numexpr cython
  # conda-forge has hdf5-1.8.17 with shared libs
  #  - cmd: conda install --yes --channel conda-forge hdf5 
  - cmd: SET HDF5_DIR=/Program Files/HDF_Group/HDF5/1.8.17/
  - cmd: echo %PATH%
  - cmd: env
  - "%CMD_IN_ENV% python setup.py build"
  - "%CMD_IN_ENV% python tables\\tests\\test_all.py --verbose"
